# Generated by Django 4.2.1 on 2023-06-05 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientsfeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_title', models.CharField(max_length=60)),
                ('feedback_author', models.CharField(max_length=90)),
                ('feedback_text', models.TextField(blank=True)),
                ('feedback_photo', models.ImageField(upload_to='feedbackphoto/%Y/%m/%d/')),
                ('feedback_mark', models.CharField(max_length=20)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('is_public', models.BooleanField(default=True)),
            ],
        ),
    ]
